name: Pasaporte_2020
description: Pasaporte Jamboree 2020 Chile

version: 1.0.0+6
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  page_transition: ^1.1.5
  shared_preferences: ^0.5.3
  carousel_pro: ^1.0.0
  cached_network_image: ^1.1.3   #Cache para imagenes cuando no hay conexion
  flutter_cache_manager: ^1.1.3 # Administrador de cache para flutter
  auto_size_text: ^2.1.0
  flutter_html: ^0.11.0  #Conversor de htl para desplegar contenido
 # sembast: ^2.1.1   #Base de datos
  flutter_platform_widgets: ^0.20.2
  progress_dialog: ^1.2.0
  google_maps_flutter: ^0.5.21+12  #Biblioteca para desplegar mapas.
  geolocator: ^5.1.5  #Biblioteca para capturar ubicacion
  android_intent: ^0.3.4+7
  tinycolor: ^1.0.2 # Permite manejar los colores para oscurecerlos o aclararlos.
  timeline_list: ^0.0.3
  photo_view: ^0.9.0
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.jpg"
  image_path_ios: "assets/icon/icon.jpg"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/carousel/
    - assets/img/inicial/
    - assets/img/jamborees/
    - assets/img/locations/
    - assets/img/panolines/
    - assets/img/senderos/
    - assets/img/subcampos/
    - assets/icon/
    - assets/icon/mapa/
    - assets/icon/numeros/
    - assets/fonts/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts: # Font utilizada en Pagina inicial y para desplegar el titulo del contenido
    - family: Gingerline DEMO Regular
      fonts:
        - asset: assets/fonts/Gingerline DEMO.otf
    - family: Aspira Nar Black
      fonts:
            - asset: assets/fonts/Aspira Narrow Black.otf
    - family: Aspira Nar Light
      fonts:
            - asset: assets/fonts/Aspira Narrow Light.otf
    - family: Aspira Nar Medium
      fonts:
            - asset: assets/fonts/Aspira Narrow Medium.otf
    - family: Aspira Nar
      fonts:
            - asset: assets/fonts/Aspira Narrow Regular.otf
    - family: Aspira Nar Thin
      fonts:
            - asset: assets/fonts/Aspira Narrow Thin.otf
    - family: BlowBrush
      fonts:
            - asset: assets/fonts/blowbrush.ttf
    - family: DK Lemon Yellow Sun
      fonts:
            - asset: assets/fonts/DK Lemon Yellow Sun.otf

